# Generated by Django 3.1.1 on 2020-09-30 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed_url', models.URLField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('site_name', models.CharField(max_length=250)),
                ('image_url', models.CharField(max_length=250)),
                ('date', models.DateField()),
            ],
        ),
    ]
