# Generated by Django 3.1.1 on 2020-09-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_parsing_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(max_length=3000),
        ),
    ]
