# Generated by Django 3.1.1 on 2020-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url_parsing_app', '0002_auto_20200930_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task',
            new_name='PageInfoModel',
        ),
    ]
